/*
 * Tests for the encoders. No dependencies — run with:  node tests/test.mjs
 *
 * Four kinds of check:
 *  1. Block layout for all 160 version/level combinations, and the published
 *     ISO/IEC 18004 character capacities.
 *  2. Byte-for-byte matrix comparison against reference vectors (vectors.json,
 *     generated by qrcodegen/segno/python-barcode — see generate-vectors.py).
 *  3. Round-trip decoding: QR matrices and Code 128 symbols are decoded back to
 *     their input by an independent reader in this file.
 *  4. Check digits, input validation and error handling.
 */
import { createRequire } from 'node:module';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const QR = require(join(here, '..', 'qr-barcode', 'qrcode.js'));
const Barcode = require(join(here, '..', 'qr-barcode', 'barcode.js'));
const vectors = JSON.parse(readFileSync(join(here, 'vectors.json'), 'utf8'));

let passed = 0;
const failures = [];

function check(name, fn) {
  try { fn(); passed++; } catch (err) { failures.push(`${name}: ${err.message}`); }
}
function assert(cond, msg) { if (!cond) throw new Error(msg || 'assertion failed'); }
function assertEqual(actual, expected, msg) {
  if (actual !== expected) {
    throw new Error(`${msg || 'mismatch'}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
  }
}

// ============================================================ 1. capacity math

check('block layout for all 160 version/level combinations', () => {
  for (let ver = 1; ver <= 40; ver++) {
    for (const lvl of ['L', 'M', 'Q', 'H']) {
      const ref = vectors.ecc_table[ver][lvl];
      assertEqual(Math.floor(QR._internal.getNumRawDataModules(ver) / 8), ref.total_codewords,
        `v${ver}-${lvl} total codewords`);
      assertEqual(QR._internal.getNumDataCodewords(ver, QR._internal.ECL[lvl]), ref.data_codewords,
        `v${ver}-${lvl} data codewords`);
    }
  }
});

// ISO/IEC 18004 Table 7: numeric / alphanumeric / byte capacity at both extremes.
const CHAR_CAPACITY = [
  [1, 'L', 41, 25, 17], [1, 'M', 34, 20, 14], [1, 'Q', 27, 16, 11], [1, 'H', 17, 10, 7],
  [40, 'L', 7089, 4296, 2953], [40, 'M', 5596, 3391, 2331],
  [40, 'Q', 3993, 2420, 1663], [40, 'H', 3057, 1852, 1273]
];

for (const [ver, lvl, numeric, alnum, byte] of CHAR_CAPACITY) {
  check(`character capacity v${ver}-${lvl}`, () => {
    // Longest string of each mode that still encodes at this version.
    const fits = (text) => {
      try {
        const qr = QR.encode(text, { ecl: lvl, maxVersion: ver, boostEcl: false });
        return qr.version <= ver;
      } catch (e) { return false; }
    };
    assert(fits('1'.repeat(numeric)), `${numeric} digits should fit`);
    assert(!fits('1'.repeat(numeric + 1)), `${numeric + 1} digits should not fit`);
    assert(fits('A'.repeat(alnum)), `${alnum} alphanumeric should fit`);
    assert(!fits('A'.repeat(alnum + 1)), `${alnum + 1} alphanumeric should not fit`);
    assert(fits('a'.repeat(byte)), `${byte} bytes should fit`);
    assert(!fits('a'.repeat(byte + 1)), `${byte + 1} bytes should not fit`);
  });
}

// ================================================== 2. QR vs reference matrices

for (const v of vectors.qr) {
  const shown = v.text.length > 22 ? v.text.slice(0, 22) + '…' : v.text;
  check(`QR matrix "${shown}" (${v.ecl}, v${v.version})`, () => {
    const qr = QR.encode(v.text, { ecl: v.ecl, boostEcl: false });
    assertEqual(qr.version, v.version, 'version');
    assertEqual(qr.mask, v.mask, 'mask');
    assertEqual(qr.size, v.matrix.length, 'size');
    for (let y = 0; y < qr.size; y++) {
      let row = '';
      for (let x = 0; x < qr.size; x++) row += qr.get(x, y) ? '1' : '0';
      assertEqual(row, v.matrix[y], `row ${y}`);
    }
  });
}

// ======================================================= 3a. QR decoder (reader)

/** Modules occupied by function patterns, derived from the version alone. */
function functionModuleMap(version) {
  const size = version * 4 + 17;
  const map = Array.from({ length: size }, () => new Array(size).fill(false));
  const mark = (x, y) => { if (x >= 0 && x < size && y >= 0 && y < size) map[y][x] = true; };

  for (let i = 0; i < size; i++) { mark(6, i); mark(i, 6); }            // timing
  for (const [cx, cy] of [[3, 3], [size - 4, 3], [3, size - 4]]) {      // finders + separators
    for (let dy = -4; dy <= 4; dy++) for (let dx = -4; dx <= 4; dx++) mark(cx + dx, cy + dy);
  }
  let positions = [];
  if (version > 1) {                                                   // alignment
    const n = Math.floor(version / 7) + 2;
    const step = version === 32 ? 26 : Math.floor((version * 4 + n * 2 + 1) / (n * 2 - 2)) * 2;
    positions = [6];
    for (let p = size - 7; positions.length < n; p -= step) positions.splice(1, 0, p);
  }
  for (let i = 0; i < positions.length; i++) {
    for (let j = 0; j < positions.length; j++) {
      const corner = (i === 0 && j === 0) || (i === 0 && j === positions.length - 1) ||
        (i === positions.length - 1 && j === 0);
      if (corner) continue;
      for (let dy = -2; dy <= 2; dy++) for (let dx = -2; dx <= 2; dx++) mark(positions[i] + dx, positions[j] + dy);
    }
  }
  for (let i = 0; i <= 8; i++) { mark(8, i); mark(i, 8); }              // format info
  for (let i = 0; i < 8; i++) { mark(size - 1 - i, 8); mark(8, size - 1 - i); }
  if (version >= 7) {                                                  // version info
    for (let i = 0; i < 18; i++) { mark(size - 11 + i % 3, Math.floor(i / 3)); mark(Math.floor(i / 3), size - 11 + i % 3); }
  }
  return map;
}

function maskBit(mask, x, y) {
  switch (mask) {
    case 0: return (x + y) % 2 === 0;
    case 1: return y % 2 === 0;
    case 2: return x % 3 === 0;
    case 3: return (x + y) % 3 === 0;
    case 4: return (Math.floor(x / 3) + Math.floor(y / 2)) % 2 === 0;
    case 5: return x * y % 2 + x * y % 3 === 0;
    case 6: return (x * y % 2 + x * y % 3) % 2 === 0;
    case 7: return ((x + y) % 2 + x * y % 3) % 2 === 0;
  }
  throw new Error('bad mask');
}

/** Read the 15 format bits back out and recover the EC level and mask. */
function readFormatInfo(get, size) {
  let bits = 0;
  for (let i = 0; i <= 5; i++) bits |= (get(8, i) ? 1 : 0) << i;
  bits |= (get(8, 7) ? 1 : 0) << 6;
  bits |= (get(8, 8) ? 1 : 0) << 7;
  bits |= (get(7, 8) ? 1 : 0) << 8;
  for (let i = 9; i < 15; i++) bits |= (get(14 - i, 8) ? 1 : 0) << i;
  const data = (bits ^ 0x5412) >>> 10;

  // Verify the BCH remainder so a corrupt format field cannot pass silently.
  let rem = data;
  for (let i = 0; i < 10; i++) rem = (rem << 1) ^ ((rem >>> 9) * 0x537);
  if ((((data << 10) | rem) ^ 0x5412) !== bits) throw new Error('format info BCH check failed');

  const ecl = { 1: 'L', 0: 'M', 3: 'Q', 2: 'H' }[data >>> 3];
  return { ecl, mask: data & 7 };
}

function decodeQr(qr) {
  const size = qr.size;
  const version = (size - 17) / 4;
  const { ecl, mask } = readFormatInfo((x, y) => qr.get(x, y), size);

  const fn = functionModuleMap(version);
  const bits = [];
  for (let right = size - 1; right >= 1; right -= 2) {
    if (right === 6) right = 5;
    for (let vert = 0; vert < size; vert++) {
      for (let j = 0; j < 2; j++) {
        const x = right - j;
        const upward = ((right + 1) & 2) === 0;
        const y = upward ? size - 1 - vert : vert;
        if (fn[y][x]) continue;
        bits.push((qr.get(x, y) !== maskBit(mask, x, y)) ? 1 : 0);
      }
    }
  }

  const codewords = [];
  for (let i = 0; i + 8 <= bits.length; i += 8) {
    let b = 0;
    for (let j = 0; j < 8; j++) b = (b << 1) | bits[i + j];
    codewords.push(b);
  }

  // De-interleave: undo the block split described in ISO 18004 7.6.
  const ref = vectors.ecc_table[version][ecl];
  const numBlocks = ref.blocks;
  const blockEccLen = ref.ecc_per_block;
  const rawCodewords = ref.total_codewords;
  const numShortBlocks = numBlocks - rawCodewords % numBlocks;
  const shortBlockLen = Math.floor(rawCodewords / numBlocks);
  const shortDataLen = shortBlockLen - blockEccLen;

  const blocks = Array.from({ length: numBlocks }, () => []);
  let idx = 0;
  for (let i = 0; i < shortBlockLen - blockEccLen + 1; i++) {
    for (let j = 0; j < numBlocks; j++) {
      if (i === shortDataLen && j < numShortBlocks) continue;
      if (i < shortDataLen + (j < numShortBlocks ? 0 : 1)) blocks[j].push(codewords[idx++]);
    }
  }
  const data = [].concat(...blocks);

  // Parse the segment stream.
  let pos = 0;
  const dataBits = [];
  for (const b of data) for (let i = 7; i >= 0; i--) dataBits.push((b >>> i) & 1);
  const take = (n) => {
    let v = 0;
    for (let i = 0; i < n; i++) v = (v << 1) | dataBits[pos++];
    return v;
  };
  const ccIndex = version <= 9 ? 0 : version <= 26 ? 1 : 2;
  const ALNUM = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ $%*+-./:';

  let bytes = [];
  let text = '';
  const flushBytes = () => {
    if (bytes.length) { text += Buffer.from(bytes).toString('utf8'); bytes = []; }
  };

  while (pos + 4 <= dataBits.length) {
    const mode = take(4);
    if (mode === 0) break; // terminator
    if (mode === 1) {
      let n = take([10, 12, 14][ccIndex]);
      flushBytes();
      while (n >= 3) { text += String(take(10)).padStart(3, '0'); n -= 3; }
      if (n === 2) text += String(take(7)).padStart(2, '0');
      else if (n === 1) text += String(take(4));
    } else if (mode === 2) {
      let n = take([9, 11, 13][ccIndex]);
      flushBytes();
      while (n >= 2) { const v = take(11); text += ALNUM[Math.floor(v / 45)] + ALNUM[v % 45]; n -= 2; }
      if (n === 1) text += ALNUM[take(6)];
    } else if (mode === 4) {
      const n = take([8, 16, 16][ccIndex]);
      for (let i = 0; i < n; i++) bytes.push(take(8));
    } else {
      throw new Error('unsupported mode ' + mode);
    }
  }
  flushBytes();
  return { text, ecl, mask, version };
}

const QR_ROUND_TRIP = [
  '', 'A', '1', 'hello', 'HELLO WORLD', '12345', '0123456789'.repeat(5),
  'https://example.com/some/path?a=1&b=2', 'Mixed 123 ABC xyz!',
  'naïve café — ünïcödé ✓ 日本語', 'emoji: 🎉🚀', 'tab\tnewline\nend',
  '$%*+-./: ABC 123', 'x'.repeat(300), 'y'.repeat(1000), '9'.repeat(2000),
  'BEGIN:VCARD\nVERSION:3.0\nN:Doe;Jane\nEND:VCARD',
  'WIFI:T:WPA;S:MyNetwork;P:s3cr3t!;;'
];

for (const text of QR_ROUND_TRIP) {
  for (const ecl of ['L', 'M', 'Q', 'H']) {
    const shown = text.length > 18 ? text.slice(0, 18) + '…' : text;
    check(`QR round-trip "${shown}" (${ecl})`, () => {
      let qr;
      try {
        qr = QR.encode(text, { ecl, boostEcl: false });
      } catch (e) {
        if (/too long/.test(e.message)) return; // legitimately over capacity
        throw e;
      }
      const decoded = decodeQr(qr);
      assertEqual(decoded.text, text, 'decoded text');
      assertEqual(decoded.ecl, ecl, 'decoded EC level');
      assertEqual(decoded.mask, qr.mask, 'decoded mask');
    });
  }
}

check('QR round-trip survives EC level boosting', () => {
  const qr = QR.encode('HELLO WORLD', { ecl: 'L', boostEcl: true });
  const decoded = decodeQr(qr);
  assertEqual(decoded.text, 'HELLO WORLD');
  assert(decoded.ecl !== 'L', 'expected the EC level to be boosted above L');
});

check('QR honours an explicitly chosen mask', () => {
  for (let mask = 0; mask < 8; mask++) {
    const qr = QR.encode('mask test 12345', { ecl: 'M', mask });
    assertEqual(qr.mask, mask, `mask ${mask}`);
    assertEqual(decodeQr(qr).text, 'mask test 12345', `data with mask ${mask}`);
  }
});

check('QR honours minVersion', () => {
  const qr = QR.encode('short', { ecl: 'M', minVersion: 10 });
  assertEqual(qr.version, 10);
  assertEqual(decodeQr(qr).text, 'short');
});

check('QR rejects data that is too long', () => {
  let threw = false;
  try { QR.encode('x'.repeat(3000), { ecl: 'H' }); } catch (e) { threw = true; }
  assert(threw, 'expected a RangeError');
});

check('QR mode selection', () => {
  assertEqual(QR._internal.makeSegment('12345').mode, 'numeric');
  assertEqual(QR._internal.makeSegment('HELLO WORLD').mode, 'alphanumeric');
  assertEqual(QR._internal.makeSegment('Hello').mode, 'byte');
  assertEqual(QR._internal.makeSegment('café').mode, 'byte');
});

check('QR numeric mode is more compact than byte mode', () => {
  const numeric = QR.encode('1'.repeat(40), { ecl: 'L', boostEcl: false });
  const byte = QR.encode('a'.repeat(40), { ecl: 'L', boostEcl: false });
  assert(numeric.version < byte.version, 'numeric should need a smaller version');
});

// ============================================= 4. barcodes vs reference vectors

for (const v of vectors.barcode) {
  check(`${v.format} "${v.value}" matches reference`, () => {
    assertEqual(Barcode.encode(v.format, v.value, v.options).binary, v.binary, 'binary');
  });
}

check('Code 128 symbol structure', () => {
  const r = Barcode.encode('code128', 'ABC');
  assertEqual(r.binary.length, 11 * (1 + 3 + 1) + 13, 'total modules');
  assert(r.binary.startsWith('11010010000'), 'Start B pattern');
  assert(r.binary.endsWith('1100011101011'), 'Stop pattern');
});

// ------------------------------------------------- Code 128 round-trip decode

const CODE128_BY_PATTERN = (() => {
  const map = new Map();
  const widths = [
    '212222', '222122', '222221', '121223', '121322', '131222', '122213', '122312', '132212', '221213',
    '221312', '231212', '112232', '122132', '122231', '113222', '123122', '123221', '223211', '221132',
    '221231', '213212', '223112', '312131', '311222', '321122', '321221', '312212', '322112', '322211',
    '212123', '212321', '232121', '111323', '131123', '131321', '112313', '132113', '132311', '211313',
    '231113', '231311', '112133', '112331', '132131', '113123', '113321', '133121', '313121', '211331',
    '231131', '213113', '213311', '213131', '311123', '311321', '331121', '312113', '312311', '332111',
    '314111', '221411', '431111', '111224', '111422', '121124', '121421', '141122', '141221', '112214',
    '112412', '122114', '122411', '142112', '142211', '241211', '221114', '413111', '241112', '134111',
    '111242', '121142', '121241', '114212', '124112', '124211', '411212', '421112', '421211', '212141',
    '214121', '412121', '111143', '111341', '131141', '114113', '114311', '411113', '411311', '113141',
    '114131', '311141', '411131', '211412', '211214', '211232', '2331112'
  ];
  widths.forEach((w, value) => {
    let bin = '', bar = true;
    for (const ch of w) { bin += (bar ? '1' : '0').repeat(Number(ch)); bar = !bar; }
    // Every symbol must be 11 modules wide (13 for the stop pattern).
    if (bin.length !== (value === 106 ? 13 : 11)) throw new Error(`symbol ${value} has ${bin.length} modules`);
    if (map.has(bin)) throw new Error(`duplicate pattern for value ${value}`);
    map.set(bin, value);
  });
  return map;
})();

function decodeCode128(binary) {
  const values = [];
  let i = 0;
  while (i < binary.length) {
    const len = binary.length - i === 13 ? 13 : 11;
    const chunk = binary.substr(i, len);
    if (!CODE128_BY_PATTERN.has(chunk)) throw new Error(`unknown symbol at ${i}: ${chunk}`);
    values.push(CODE128_BY_PATTERN.get(chunk));
    i += len;
  }
  assertEqual(values.pop(), 106, 'stop symbol');
  const checksum = values.pop();
  let sum = values[0];
  for (let k = 1; k < values.length; k++) sum += values[k] * k;
  assertEqual(sum % 103, checksum, 'checksum');

  let set = { 103: 'A', 104: 'B', 105: 'C' }[values[0]];
  assert(set, 'start symbol');
  let text = '';
  for (let k = 1; k < values.length; k++) {
    const v = values[k];
    if (set !== 'C' && v === 99) { set = 'C'; continue; }
    if (set !== 'B' && v === 100) { set = 'B'; continue; }
    if (set !== 'A' && v === 101) { set = 'A'; continue; }
    if (set === 'C') text += String(v).padStart(2, '0');
    else if (set === 'B') text += String.fromCharCode(v + 32);
    else text += String.fromCharCode(v < 64 ? v + 32 : v - 64);
  }
  return text;
}

const CODE128_ROUND_TRIP = [
  'Hello', 'A', '1', '12', '123', '1234', '12345', '123456', '1234567890123456789',
  'ABC-123', 'a1b2c3', 'Item 42: $9.99', 'X1234567890Y', 'PO#12345678/2024',
  'abc123456789def', '00000000', 'MiXeD CaSe 999 !@#', 'AB12CD34EF56', 'tab\tseparated',
  'https://example.com/p/12345', '9'.repeat(40), 'Q'.repeat(30) + '1'.repeat(30),
  '1a', 'a1', '12a34', 'SKU-0001-A', '~del'
];

for (const text of CODE128_ROUND_TRIP) {
  const shown = text.length > 20 ? text.slice(0, 20) + '…' : text;
  check(`Code 128 round-trip "${shown}"`, () => {
    assertEqual(decodeCode128(Barcode.encode('code128', text).binary), text, 'decoded text');
  });
}

// ===================================================== 5. check digits & errors

check('GS1 check digits', () => {
  assertEqual(Barcode.gs1CheckDigit('123456789012'), '8');
  assertEqual(Barcode.gs1CheckDigit('400638133393'), '1');
  assertEqual(Barcode.gs1CheckDigit('9638507'), '4');
  assertEqual(Barcode.gs1CheckDigit('03600029145'), '2');
  assertEqual(Barcode.gs1CheckDigit('01234567890'), '5');
});

check('EAN-13 computes a missing check digit', () => {
  const withCheck = Barcode.encode('ean13', '4006381333931');
  const without = Barcode.encode('ean13', '400638133393');
  assertEqual(without.binary, withCheck.binary, 'binary');
  assertEqual(without.displayText, '4006381333931', 'display text');
});

check('EAN-13 rejects a wrong check digit', () => {
  let msg = '';
  try { Barcode.encode('ean13', '4006381333930'); } catch (e) { msg = e.message; }
  assert(/check digit should be 1/.test(msg), `unexpected error: ${msg}`);
});

check('EAN-13 rejects the wrong length', () => {
  for (const bad of ['12345', '12345678901234']) {
    let threw = false;
    try { Barcode.encode('ean13', bad); } catch (e) { threw = true; }
    assert(threw, `accepted "${bad}"`);
  }
});

check('EAN-13 ignores spaces and dashes', () => {
  assertEqual(Barcode.encode('ean13', '400-638 133 3931').binary,
    Barcode.encode('ean13', '4006381333931').binary);
});

check('EAN symbol widths', () => {
  assertEqual(Barcode.encode('ean13', '4006381333931').binary.length, 95);
  assertEqual(Barcode.encode('ean8', '96385074').binary.length, 67);
  assertEqual(Barcode.encode('upca', '012345678905').binary.length, 95);
});

check('UPC-A is EAN-13 with a leading zero', () => {
  assertEqual(Barcode.encode('upca', '012345678905').binary,
    Barcode.encode('ean13', '0012345678905').binary);
});

check('ITF pads odd-length input', () => {
  assertEqual(Barcode.encode('itf', '123').displayText, '0123');
});

check('ITF-14 check digit', () => {
  const r = Barcode.encode('itf14', '1234567890123');
  assertEqual(r.displayText, '12345678901231');
  assert(r.bearerBar, 'ITF-14 should request a bearer bar');
});

check('ITF-14 rejects a wrong check digit', () => {
  let threw = false;
  try { Barcode.encode('itf14', '12345678901230'); } catch (e) { threw = true; }
  assert(threw);
});

check('Code 39 uppercases input and can add a check digit', () => {
  assertEqual(Barcode.encode('code39', 'abc').displayText, '*ABC*');
  assertEqual(Barcode.encode('code39', 'ABC', { checkDigit: true }).displayText, '*ABCX*');
  assertEqual(Barcode.encode('code39', 'code39 test', { checkDigit: true }).displayText, '*CODE39 TEST+*');
});

check('Code 39 rejects unsupported characters', () => {
  for (const bad of ['a!b', 'lower_case', 'a#b']) {
    let threw = false;
    try { Barcode.encode('code39', bad); } catch (e) { threw = true; }
    assert(threw, `accepted "${bad}"`);
  }
});

check('Code 128 rejects non-ASCII', () => {
  let msg = '';
  try { Barcode.encode('code128', 'café'); } catch (e) { msg = e.message; }
  assert(/ASCII/.test(msg), `unexpected error: ${msg}`);
});

check('unknown format is rejected', () => {
  let threw = false;
  try { Barcode.encode('qr-but-not', '123'); } catch (e) { threw = true; }
  assert(threw);
});

check('empty input is rejected', () => {
  for (const fmt of Object.keys(Barcode.formats)) {
    let threw = false;
    try { Barcode.encode(fmt, ''); } catch (e) { threw = true; }
    assert(threw, `${fmt} accepted empty input`);
  }
});

check('non-digit input is rejected by numeric formats', () => {
  for (const fmt of ['ean13', 'ean8', 'upca', 'itf', 'itf14']) {
    let threw = false;
    try { Barcode.encode(fmt, 'ABC123'); } catch (e) { threw = true; }
    assert(threw, `${fmt} accepted letters`);
  }
});

// ============================================================ results

console.log(`\n${passed} passed, ${failures.length} failed`);
if (failures.length) {
  console.log('\nFailures:');
  for (const f of failures) console.log('  ✗ ' + f);
  process.exit(1);
}
